# SPDX-FileCopyrightText: © 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "embedded-storage-fs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
embedded-storage = "0.3"
