#!/bin/bash
# SPDX-FileCopyrightText: 2021 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

branch=`git symbolic-ref HEAD`
if [ "$branch" = "refs/heads/main" ] || [[ "$branch" == refs/heads/dev-v* ]]; then
    echo "Direct commits to the main and dev branches are not allowed."
    exit 1
fi

RESULTS=$(find . -name '*.py' -exec grep -H fake_it[\ ]*=[\ ]*True {} +)
LEN=`expr length "$RESULTS"`
echo $RESULTS
# echo $LEN
if [[ $LEN -gt 0 ]]; then
  echo
  echo -e "\n======================================================" >&2
  echo -e "ERROR: Never commit code with fake seeds or passwords!" >&2
  echo -e "======================================================\n" >&2
  exit 1
fi

# Check lints
echo Running lints...
just ports/stm32/lint
if [ $? -eq 0 ]
then
  echo -e "Lint succeeded."
  exit 0
else
  echo -e "\n=======================================================" >&2
  echo -e "Lint failed.  Fix the issues shown above and try again." >&2
  echo -e "=======================================================\n" >&2
  exit 1
fi
