# SPDX-FileCopyrightText: © 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "cmsis-device-h7-sys"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
