// SPDX-FileCopyrightText: © 2022 Foundation Devices, Inc. <hello@foundationdevices.com>
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Autogenerated by ports/stm32/Justfile images command -- DO NOT EDIT MANUALLY!
//

#ifdef SCREEN_MODE_COLOR
extern const lv_img_dsc_t BACKGROUND;
extern const lv_img_dsc_t ICON_ABOUT;
extern const lv_img_dsc_t ICON_BACK;
extern const lv_img_dsc_t ICON_CANCEL;
extern const lv_img_dsc_t ICON_CHECKMARK;
extern const lv_img_dsc_t ICON_EMAIL;
extern const lv_img_dsc_t ICON_EXIT;
extern const lv_img_dsc_t ICON_FORWARD;
extern const lv_img_dsc_t ICON_PAGE_DOT_SELECTED;
extern const lv_img_dsc_t ICON_PAGE_DOT;
extern const lv_img_dsc_t ICON_RETRY;
extern const lv_img_dsc_t ICON_SHUTDOWN;
extern const lv_img_dsc_t LARGE_ICON_ERROR;
extern const lv_img_dsc_t LARGE_ICON_INFO;
extern const lv_img_dsc_t LARGE_ICON_MICROSD;
extern const lv_img_dsc_t LARGE_ICON_QUESTION;
extern const lv_img_dsc_t PROGRESS_BAR_BG;
extern const lv_img_dsc_t PROGRESS_BAR_FG;
extern const lv_img_dsc_t PROGRESS_CAP_LEFT;
extern const lv_img_dsc_t PROGRESS_CAP_RIGHT_BG;
extern const lv_img_dsc_t PROGRESS_CAP_RIGHT;
extern const lv_img_dsc_t SPLASH;
#endif

