# SPDX-FileCopyrightText: © 2022 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# colors.py

# Standard color bible

import lvgl as lv
import passport

# Sometimes we need just the hex value, so we define them separately, but
# also define an actual LVGL color object.

if passport.IS_COLOR:
    # Shades of grey
    WHITE_HEX = 0xFFFFFF
    BLACK_HEX = 0x000000

    VERY_LIGHT_GREY_HEX = 0xF0F0F0
    LIGHT_GREY_HEX = 0xDDDDDD
    MEDIUM_GREY_HEX = 0xA0A0A0
    MICRON_GREY_HEX = 0x808080
    TEXT_GREY_HEX = 0x6D6D6D
    DARK_GREY_HEX = 0x626262
    CHARCOAL_HEX = 0x262626
    RED_HEX = 0xFF0000
    GREEN_HEX = 0x00BB00
    BLUE_HEX = 0x0000FF
    FD_BLUE_HEX = 0x00BDCD
    FD_LIGHT_BLUE_HEX = 0x55EFFC
    FD_DARK_BLUE_HEX = 0x005d64
    COPPER_HEX = 0xBF755F
    LIGHT_COPPER_HEX = 0xD2A794
    BITCOIN_ORANGE_HEX = 0xF2A900

    CARD_BG_GREY_HEX = 0xF9F7F6
    CARD_BORDER_HEX = 0xFEFEFE
    NORMAL_TEXT_HEX = TEXT_GREY_HEX
    LIGHT_TEXT_HEX = TEXT_GREY_HEX
    SPINNER_BG_HEX = 0xE0E0E0
    HIGHLIGHT_TEXT_HEX = FD_BLUE_HEX
    MENU_ITEM_BG_HEX = FD_BLUE_HEX
    TEXT_INPUT_BG_HEX = LIGHT_GREY_HEX
    TEXT_INPUT_TEXT_HEX = NORMAL_TEXT_HEX
    TEXT_INPUT_ICON_HEX = FD_BLUE_HEX
    TEXT_INPUT_CURSOR_HEX = FD_BLUE_HEX
    DEFAULT_SPINNER_HEX = FD_BLUE_HEX
    CHOOSER_ICON_HEX = FD_BLUE_HEX
    FOCUSED_LIST_ITEM_BG_HEX = FD_BLUE_HEX
    FOCUSED_LIST_ITEM_TEXT_HEX = WHITE_HEX
    DEFAULT_LARGE_ICON_COLOR_HEX = FD_BLUE_HEX
    SWITCH_BG_CHECKED_HEX = FD_BLUE_HEX
    SWITCH_BG_UNCHECKED_HEX = MICRON_GREY_HEX
    SWITCH_BORDER_HEX = WHITE_HEX
    SWITCH_KNOB_HEX = WHITE_HEX
    CARD_HEADER_TEXT_HEX = TEXT_GREY_HEX
    SYMBOL_PICKER_TEXT_HEX = TEXT_GREY_HEX
    BACKUP_CODE_DIGIT_HEX = TEXT_GREY_HEX
    BACKUP_CODE_DIGIT_FOCUSED_HEX = TEXT_GREY_HEX
    BACKUP_CODE_SECTION_BG_HEX = VERY_LIGHT_GREY_HEX
    BACKUP_CODE_SECTION_OUTLINE_HEX = FD_BLUE_HEX
    DIGIT_BORDER_COLOR_UNFOCUSED_HEX = LIGHT_GREY_HEX
    DIGIT_BORDER_COLOR_FOCUSED_HEX = FD_BLUE_HEX
    PIN_ENTRY_MESSAGE_COLOR_HEX = FD_BLUE_HEX
    BATTERY_FILL_COLOR_HEX = FD_BLUE_HEX
    BATTERY_FILL_BG_COLOR_HEX = TEXT_GREY_HEX
    SCROLLBAR_BG_COLOR_HEX = BLACK_HEX
else:
    # On monochrome, white is white, and everything else is black
    # Shades of grey
    invert = False
    if invert:
        WHITE_HEX = 0x000000
        BLACK_HEX = 0xFFFFFF
    else:
        WHITE_HEX = 0xFFFFFF
        BLACK_HEX = 0x000000

    VERY_LIGHT_GREY_HEX = BLACK_HEX
    LIGHT_GREY_HEX = BLACK_HEX
    MEDIUM_GREY_HEX = BLACK_HEX
    MICRON_GREY_HEX = WHITE_HEX
    TEXT_GREY_HEX = BLACK_HEX
    DARK_GREY_HEX = BLACK_HEX
    CHARCOAL_HEX = BLACK_HEX
    RED_HEX = BLACK_HEX
    GREEN_HEX = BLACK_HEX
    BLUE_HEX = BLACK_HEX
    FD_BLUE_HEX = WHITE_HEX
    FD_LIGHT_BLUE_HEX = BLACK_HEX
    FD_DARK_BLUE_HEX = BLACK_HEX
    COPPER_HEX = BLACK_HEX
    LIGHT_COPPER_HEX = BLACK_HEX
    BITCOIN_ORANGE_HEX = BLACK_HEX

    CARD_BG_GREY_HEX = BLACK_HEX
    CARD_BORDER_HEX = BLACK_HEX
    NORMAL_TEXT_HEX = BLACK_HEX
    LIGHT_TEXT_HEX = WHITE_HEX
    SPINNER_BG_HEX = WHITE_HEX
    HIGHLIGHT_TEXT_HEX = BLACK_HEX
    MENU_ITEM_BG_HEX = BLACK_HEX
    TEXT_INPUT_BG_HEX = BLACK_HEX
    TEXT_INPUT_TEXT_HEX = WHITE_HEX
    TEXT_INPUT_ICON_HEX = WHITE_HEX
    TEXT_INPUT_CURSOR_HEX = WHITE_HEX
    DEFAULT_SPINNER_HEX = BLACK_HEX
    CHOOSER_ICON_HEX = BLACK_HEX
    FOCUSED_LIST_ITEM_BG_HEX = BLACK_HEX
    FOCUSED_LIST_ITEM_TEXT_HEX = WHITE_HEX
    DEFAULT_LARGE_ICON_COLOR_HEX = BLACK_HEX
    SWITCH_BG_CHECKED_HEX = WHITE_HEX
    SWITCH_BG_UNCHECKED_HEX = WHITE_HEX
    SWITCH_BORDER_HEX = BLACK_HEX
    SWITCH_KNOB_HEX = BLACK_HEX
    CARD_HEADER_TEXT_HEX = WHITE_HEX
    SYMBOL_PICKER_TEXT_HEX = WHITE_HEX
    BACKUP_CODE_DIGIT_HEX = BLACK_HEX
    BACKUP_CODE_DIGIT_FOCUSED_HEX = WHITE_HEX
    BACKUP_CODE_SECTION_BG_HEX = WHITE_HEX
    BACKUP_CODE_SECTION_OUTLINE_HEX = BLACK_HEX
    DIGIT_BORDER_COLOR_FOCUSED_HEX = BLACK_HEX
    DIGIT_BORDER_COLOR_UNFOCUSED_HEX = BLACK_HEX
    PIN_ENTRY_MESSAGE_COLOR_HEX = BLACK_HEX
    BATTERY_FILL_COLOR_HEX = WHITE_HEX
    BATTERY_FILL_BG_COLOR_HEX = BLACK_HEX
    SCROLLBAR_BG_COLOR_HEX = BLACK_HEX

WHITE = lv.color_hex(WHITE_HEX)
VERY_LIGHT_GREY = lv.color_hex(VERY_LIGHT_GREY_HEX)
LIGHT_GREY = lv.color_hex(LIGHT_GREY_HEX)
MEDIUM_GREY = lv.color_hex(MEDIUM_GREY_HEX)
MICRON_GREY = lv.color_hex(MICRON_GREY_HEX)
TEXT_GREY = lv.color_hex(TEXT_GREY_HEX)
DARK_GREY = lv.color_hex(DARK_GREY_HEX)
CHARCOAL = lv.color_hex(CHARCOAL_HEX)
BLACK = lv.color_hex(BLACK_HEX)

# Primary colors (mostly for debugging)
RED = lv.color_hex(RED_HEX)
GREEN = lv.color_hex(GREEN_HEX)
BLUE = lv.color_hex(BLUE_HEX)

# Brand colors
FD_BLUE = lv.color_hex(FD_BLUE_HEX)
FD_LIGHT_BLUE = lv.color_hex(FD_LIGHT_BLUE_HEX)
FD_DARK_BLUE = lv.color_hex(FD_DARK_BLUE_HEX)
COPPER = lv.color_hex(COPPER_HEX)
LIGHT_COPPER = lv.color_hex(LIGHT_COPPER_HEX)
BITCOIN_ORANGE = lv.color_hex(BITCOIN_ORANGE_HEX)

# Component colors
CARD_BG_GREY = lv.color_hex(CARD_BG_GREY_HEX)
CARD_BORDER = lv.color_hex(CARD_BORDER_HEX)
NORMAL_TEXT = lv.color_hex(NORMAL_TEXT_HEX)
LIGHT_TEXT = lv.color_hex(LIGHT_TEXT_HEX)
HIGHLIGHT_TEXT = lv.color_hex(HIGHLIGHT_TEXT_HEX)
SPINNER_BG = lv.color_hex(SPINNER_BG_HEX)
MENU_ITEM_BG = lv.color_hex(MENU_ITEM_BG_HEX)
DEFAULT_SPINNER = lv.color_hex(DEFAULT_SPINNER_HEX)
TEXT_INPUT_BG = lv.color_hex(TEXT_INPUT_BG_HEX)
TEXT_INPUT_TEXT = lv.color_hex(TEXT_INPUT_TEXT_HEX)
TEXT_INPUT_ICON = lv.color_hex(TEXT_INPUT_ICON_HEX)
TEXT_INPUT_CURSOR = lv.color_hex(TEXT_INPUT_CURSOR_HEX)
CHOOSER_ICON = lv.color_hex(CHOOSER_ICON_HEX)
FOCUSED_LIST_ITEM_BG = lv.color_hex(FOCUSED_LIST_ITEM_BG_HEX)
FOCUSED_LIST_ITEM_TEXT = lv.color_hex(FOCUSED_LIST_ITEM_TEXT_HEX)
DEFAULT_LARGE_ICON_COLOR = lv.color_hex(DEFAULT_LARGE_ICON_COLOR_HEX)
SWITCH_BG_CHECKED = lv.color_hex(SWITCH_BG_CHECKED_HEX)
SWITCH_BG_UNCHECKED = lv.color_hex(SWITCH_BG_UNCHECKED_HEX)
SWITCH_BORDER = lv.color_hex(SWITCH_BORDER_HEX)
SWITCH_KNOB = lv.color_hex(SWITCH_KNOB_HEX)
CARD_HEADER_TEXT = lv.color_hex(CARD_HEADER_TEXT_HEX)
SYMBOL_PICKER_TEXT = lv.color_hex(SYMBOL_PICKER_TEXT_HEX)
BACKUP_CODE_DIGIT = lv.color_hex(BACKUP_CODE_DIGIT_HEX)
BACKUP_CODE_DIGIT_FOCUSED = lv.color_hex(BACKUP_CODE_DIGIT_FOCUSED_HEX)
BACKUP_CODE_SECTION_BG = lv.color_hex(BACKUP_CODE_SECTION_BG_HEX)
BACKUP_CODE_SECTION_OUTLINE = lv.color_hex(BACKUP_CODE_SECTION_OUTLINE_HEX)
DIGIT_BORDER_COLOR_FOCUSED = lv.color_hex(DIGIT_BORDER_COLOR_FOCUSED_HEX)
DIGIT_BORDER_COLOR_UNFOCUSED = lv.color_hex(DIGIT_BORDER_COLOR_UNFOCUSED_HEX)
PIN_ENTRY_MESSAGE_COLOR = lv.color_hex(PIN_ENTRY_MESSAGE_COLOR_HEX)
BATTERY_FILL_COLOR = lv.color_hex(BATTERY_FILL_COLOR_HEX)
BATTERY_FILL_BG_COLOR = lv.color_hex(BATTERY_FILL_BG_COLOR_HEX)
SCROLLBAR_BG_COLOR = lv.color_hex(SCROLLBAR_BG_COLOR_HEX)

# Account Colors
if passport.IS_SIMULATOR:
    # if common.is_color:
    ACCOUNT_COLORS = [
        {'bg': lv.color_hex(0xBF755F), 'fg': WHITE},
        {'bg': lv.color_hex(0x009DB9), 'fg': WHITE},
        {'bg': lv.color_hex(0x007A7A), 'fg': WHITE},
        {'bg': lv.color_hex(0xD68B6E), 'fg': WHITE},
        {'bg': lv.color_hex(0x00BDCD), 'fg': WHITE},
        {'bg': lv.color_hex(0x2B8A7A), 'fg': WHITE},

    ]

    # Special colors
    CASA_PURPLE_HEX = 0x865EFC
    CASA_PURPLE = lv.color_hex(CASA_PURPLE_HEX)

    THEYA_YELLOW_HEX = 0xE99F47
    THEYA_YELLOW = lv.color_hex(THEYA_YELLOW_HEX)
else:
    ACCOUNT_COLORS = [
        {'bg': lv.color_hex(0xB04C40), 'fg': WHITE},
        {'bg': lv.color_hex(0x007088), 'fg': WHITE},
        {'bg': lv.color_hex(0x086C60), 'fg': WHITE},
        {'bg': lv.color_hex(0xF06448), 'fg': WHITE},
        {'bg': lv.color_hex(0x00A0A8), 'fg': WHITE},
        {'bg': lv.color_hex(0x087C68), 'fg': WHITE},
    ]

    # Special colors
    CASA_PURPLE_HEX = 0x966EFC
    CASA_PURPLE = lv.color_hex(CASA_PURPLE_HEX)

    THEYA_YELLOW_HEX = 0xE99F47
    THEYA_YELLOW = lv.color_hex(THEYA_YELLOW_HEX)
