# SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

[target.thumbv7em-none-eabihf]
rustflags = [
    "--cfg", "dtcm",
    "--cfg", "sram4",
]
