# SPDX-FileCopyrightText: © 2022 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# en.py - String translations for EN language code
#
# AUTOGENERATED FILE!  DO NOT EDIT MANUALLY!
#

from .tags import T

EN_TRANSLATIONS = {
    T.import_pp_intro_card1_heading: '''Pair Passport with Envoy''',
    T.import_pp_intro_card1_subheading: '''On Passport, select Pair Wallet > Envoy''',
    T.import_pp_intro_card2_subheading: '''If you want to use Envoy for firmware updates only, feel free to skip this step.''',
    T.import_pp_intro_cta: '''Get Started''',
    T.import_pp_intro_os_clock: '''9:41''',
    T.import_pp_intro_right_action: '''Skip''',
    T.import_pp_scan_cta: '''Continue''',
    T.import_pp_scan_heading: '''Scan the QR code that Passport generates''',
    T.import_pp_scan_os_clock: '''9:41''',
    T.import_pp_scan_right_action: '''Skip''',
    T.import_pp_scan_subheading: '''This QR code contains the information required for Envoy to interact securley with Passport.''',
    T.wallet_address_verify_confirm_cta: '''Continue''',
    T.wallet_address_verify_confirm_cta1: '''Contact support''',
    T.wallet_address_verify_confirm_heading: '''Address Validated?''',
    T.wallet_address_verify_confirm_os_clock: '''9:41''',
    T.wallet_address_verify_confirm_right_action: '''Skip''',
    T.wallet_address_verify_confirm_subheading: '''If you get a success message on Passport, your setup is now complete.

If Passport could not verify the address, please try again or contact support.''',
    T.wallet_address_verify_cta: '''Continue''',
    T.wallet_address_verify_heading: '''Scan this QR code with Passport to validate''',
    T.wallet_address_verify_os_clock: '''9:41''',
    T.wallet_address_verify_right_action: '''Skip''',
    T.wallet_address_verify_subheading: '''This is the first receive address controlled by your Passport.''',
    T.wallet_pair_success_cta: '''Validate Receiving address''',
    T.wallet_pair_success_cta1: '''Continue to home screen''',
    T.wallet_pair_success_heading: '''Connection successful''',
    T.wallet_pair_success_os_clock: '''9:41''',
    T.wallet_pair_success_right_action: '''Skip''',
    T.wallet_pair_success_subheading: '''Envoy has the information required to generate addresses and construct transactions for Passport. You can validate this on the following screen or skip straight to home''',
}
