# SPDX-FileCopyrightText: © 2022 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# tags.py
#
# Text tag names used in all translation files.
#
# AUTOGENERATED FILE!  DO NOT EDIT MANUALLY!
#

from Enum import enum

T = enum(
    'import_pp_intro_card1_heading',
    'import_pp_intro_card1_subheading',
    'import_pp_intro_card2_subheading',
    'import_pp_intro_cta',
    'import_pp_intro_os_clock',
    'import_pp_intro_right_action',
    'import_pp_scan_cta',
    'import_pp_scan_heading',
    'import_pp_scan_os_clock',
    'import_pp_scan_right_action',
    'import_pp_scan_subheading',
    'wallet_address_verify_confirm_cta',
    'wallet_address_verify_confirm_cta1',
    'wallet_address_verify_confirm_heading',
    'wallet_address_verify_confirm_os_clock',
    'wallet_address_verify_confirm_right_action',
    'wallet_address_verify_confirm_subheading',
    'wallet_address_verify_cta',
    'wallet_address_verify_heading',
    'wallet_address_verify_os_clock',
    'wallet_address_verify_right_action',
    'wallet_address_verify_subheading',
    'wallet_pair_success_cta',
    'wallet_pair_success_cta1',
    'wallet_pair_success_heading',
    'wallet_pair_success_os_clock',
    'wallet_pair_success_right_action',
    'wallet_pair_success_subheading',
)
