# SPDX-FileCopyrightText: © 2024 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "stm32h7xx-hal-driver-sys"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
