# SPDX-FileCopyrightText: © 2026 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Simulator tests
on: [push, pull_request]

jobs:
  simulator-tests-pass:
    name: Simulator tests pass?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - run: sudo apt-get install -y xvfb
      - run: xvfb-run -a nix develop .#build -c just test
