# SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

alias g := generate
alias b := build
alias l := lint

# Generate C bindings header.
generate:
    ./bindgen.sh
    cbindgen --config cbindgen.toml \
             --crate foundation \
             --output include/foundation.h

# Build the crate.
build:
    cargo build --target thumbv7em-none-eabihf --release

# Lint the crate.
lint:
    CC=arm-none-eabi-gcc cargo clippy --target thumbv7em-none-eabihf
    cargo fmt --check
    ./bindgen.sh -c
    cbindgen --config cbindgen.toml \
             --crate foundation \
             --output include/foundation.h \
             --verify
    CC=gcc cargo test --features std

# Print size information
sizes:
    CC=gcc cargo run --features std
