# SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

alias g := generate
alias b := build
alias l := lint

# Generate C bindings header.
generate:
    cbindgen --config cbindgen.toml \
             --crate foundation \
             --output include/foundation.h

# Build the crate.
build:
    cargo build --locked --target thumbv7em-none-eabihf --release

# Lint the crate.
lint:
    cargo clippy --locked --target thumbv7em-none-eabihf
    cargo fmt --check
    cbindgen --config cbindgen.toml \
             --crate foundation \
             --output include/foundation.h \
             --verify
    cargo test --locked --features std

# Print size information
sizes:
    cargo run --locked --features std
